"""Create Seller Table, and Update tables 2

Revision ID: 262d6a8ac462
Revises: 6913fa065c84
Create Date: 2025-12-27 23:08:58.429286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262d6a8ac462'
down_revision: Union[str, Sequence[str], None] = '6913fa065c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_seller_use_id'), table_name='seller')
    op.create_index(op.f('ix_seller_user_id'), 'seller', ['user_id'], unique=False)
    op.drop_constraint(op.f('seller_use_id_fkey'), 'seller', type_='foreignkey')
    op.create_foreign_key(None, 'seller', 'user', ['user_id'], ['id'])
    op.drop_column('seller', 'use_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('use_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'seller', type_='foreignkey')
    op.create_foreign_key(op.f('seller_use_id_fkey'), 'seller', 'user', ['use_id'], ['id'])
    op.drop_index(op.f('ix_seller_user_id'), table_name='seller')
    op.create_index(op.f('ix_seller_use_id'), 'seller', ['use_id'], unique=False)
    op.drop_column('seller', 'user_id')
    # ### end Alembic commands ###
