"""New Age

Revision ID: 6797a9733fdb
Revises: db6fc03506f9
Create Date: 2026-01-12 22:59:13.935313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6797a9733fdb'
down_revision: Union[str, Sequence[str], None] = 'db6fc03506f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('profile_photo', sa.String(), nullable=False),
    sa.Column('public_photo_id', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'SELLER', 'BUYER', name='userrole'), nullable=False),
    sa.Column('activate', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('photosproduct',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('public_photo_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photosproduct_id'), 'photosproduct', ['id'], unique=False)
    op.create_foreign_key(None, 'order', 'user', ['buyer_id'], ['id'])
    op.add_column('seller', sa.Column('profile_or_logo_photo_urls', sa.String(), nullable=False))
    op.create_foreign_key(None, 'seller', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seller', type_='foreignkey')
    op.drop_column('seller', 'profile_or_logo_photo_urls')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_index(op.f('ix_photosproduct_id'), table_name='photosproduct')
    op.drop_table('photosproduct')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
