"""Create Seller Table, and Update tables

Revision ID: 6913fa065c84
Revises: 8a952ce91da5
Create Date: 2025-12-27 23:03:53.342026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6913fa065c84'
down_revision: Union[str, Sequence[str], None] = '8a952ce91da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('use_id', sa.Integer(), nullable=False),
    sa.Column('seller_name', sa.String(), nullable=False),
    sa.Column('number_phone', sa.String(), nullable=True),
    sa.Column('email_seller', sa.String(), nullable=False),
    sa.Column('locate', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['use_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_id'), 'seller', ['id'], unique=False)
    op.create_index(op.f('ix_seller_use_id'), 'seller', ['use_id'], unique=False)
    op.add_column('product', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('detail', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('product_seller_fkey'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'seller', ['seller_id'], ['id'])
    op.drop_column('product', 'seller')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('seller', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_seller_fkey'), 'product', 'user', ['seller'], ['id'])
    op.drop_column('product', 'detail')
    op.drop_column('product', 'seller_id')
    op.drop_index(op.f('ix_seller_use_id'), table_name='seller')
    op.drop_index(op.f('ix_seller_id'), table_name='seller')
    op.drop_table('seller')
    # ### end Alembic commands ###
