"""Init Real Migrate

Revision ID: db6fc03506f9
Revises: 
Create Date: 2026-01-01 22:44:51.034297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6fc03506f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SELLER', 'BUYER', name='userrole'), nullable=False),
    sa.Column('activate', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('seller',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('seller_name', sa.String(), nullable=False),
    sa.Column('number_phone', sa.String(), nullable=True),
    sa.Column('email_seller', sa.String(), nullable=False),
    sa.Column('locate', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_id'), 'seller', ['id'], unique=False)
    op.create_index(op.f('ix_seller_user_id'), 'seller', ['user_id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=True),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('price_total', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('CANCELED', 'SUCCESSED', 'PENDENT', name='statusorder'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_buyer_id'), 'order', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('qtd_stock', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('HEAD', 'FOOT', 'BODY', name='categorydress'), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_table('item_order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('name_product', sa.String(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('qtd_item', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_order_id'), 'item_order', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_order_id'), table_name='item_order')
    op.drop_table('item_order')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_buyer_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_seller_user_id'), table_name='seller')
    op.drop_index(op.f('ix_seller_id'), table_name='seller')
    op.drop_table('seller')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
