"""base_atualizada

Revision ID: 1d0f284ed767
Revises: 
Create Date: 2026-01-21 00:12:28.593452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0f284ed767'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=True),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('price_total', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('CANCELED', 'SUCCESSED', 'PENDENT', name='statusorder'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_buyer_id'), 'order', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    # op.alter_column('item_order', 'order_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Uuid(),
    #            existing_nullable=False)
    op.execute('ALTER TABLE item_order ALTER COLUMN order_id TYPE uuid USING (order_id::text::uuid)')
    op.create_foreign_key(None, 'item_order', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_order', type_='foreignkey')
    op.alter_column('item_order', 'order_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_buyer_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
