"""Try create Tables

Revision ID: 839ba0c191b7
Revises: 
Create Date: 2026-04-23 00:06:10.157722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839ba0c191b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    UserRole = sa.Enum('ADMIN', 'SELLER', 'BUYER',name= 'userrole').create(op.get_bind())
    GenIdent = sa.Enum('MALE', 'FEMALE', 'UNISEX', 'UNDEFINED',name='genident').create(op.get_bind())
    StatusOrder = sa.Enum('CANCELED', 'COMPLETED', 'AWAITING_PAYMENT', 'PEMDENT', 'PAID', 'REFUNED',name='statusorder').create(op.get_bind())
    CategoryDress = sa.Enum('HEAD', 'BODY', 'FOOT',name='categorydress').create(op.get_bind())

    op.create_table('category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('photosproduct',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('public_photo_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photosproduct_id'), 'photosproduct', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('qtd_stock', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=False),
   sa.Column('category', sa.Enum('HEAD', 'BODY', 'FOOT', name='categorydress', ), nullable=True),
    sa.Column('target_genre', sa.Enum('MALE', 'FEMALE', 'UNISEX', 'UNDEFINED', name='genident', ), server_default='UNDEFINED', nullable=False),
    sa.Column('disponible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_table('seller',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number_phone', sa.String(), nullable=True),
    sa.Column('email_seller', sa.String(), nullable=False),
    sa.Column('locate', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('profile_or_logo_photo_urls', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_id'), 'seller', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('public_photo_id', sa.String(), nullable=True),
    sa.Column('genre', sa.Enum('MALE', 'FEMALE', 'UNISEX', 'UNDEFINED', name='genident', ), server_default='UNDEFINED', nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SELLER', 'BUYER', name='userrole', ), server_default='BUYER', nullable=False),
    sa.Column('activate', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('price_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CANCELED', 'COMPLETED', 'AWAITING_PAYMENT', 'PEMDENT', 'PAID', 'REFUNED', name='statusorder',), server_default='PENDENT', nullable=False),
    sa.Column('secret_hash', sa.String(), nullable=True),
    sa.Column('delivery_code', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_table('item_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('name_product', sa.String(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('qtd_item', sa.Integer(), nullable=False),
    sa.Column('each_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('name_product_snapshot', sa.String(), nullable=False),
    sa.Column('price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_order_id'), 'item_order', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    UserRole = sa.Enum('ADMIN', 'SELLER', 'BUYER',name= 'userrole').drop(op.get_bind())
    GenIdent = sa.Enum('MALE', 'FEMALE', 'UNISEX', 'UNDEFINED',name='genident').drop(op.get_bind())
    StatusOrder = sa.Enum('CANCELED', 'COMPLETED', 'AWAITING_PAYMENT', 'PEMDENT', 'PAID', 'REFUNED',name='statusorder').drop(op.get_bind())
    CategoryDress = sa.Enum('HEAD', 'BODY', 'FOOT',name='categorydress').drop(op.get_bind())

    op.drop_index(op.f('ix_item_order_id'), table_name='item_order')
    op.drop_table('item_order')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_seller_id'), table_name='seller')
    op.drop_table('seller')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_photosproduct_id'), table_name='photosproduct')
    op.drop_table('photosproduct')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
