"""add_order_security_fields2

Revision ID: cbfe41b35628
Revises: 1d0f284ed767
Create Date: 2026-01-31 23:16:32.038177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfe41b35628'
down_revision: Union[str, Sequence[str], None] = '1d0f284ed767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('secret_hash', sa.String(), nullable=True))
    op.add_column('order', sa.Column('paid_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'paid_at')
    op.drop_column('order', 'secret_hash')
    # ### end Alembic commands ###
